### ISSUE TITLE
Linker error on MacOS 13

### ISSUE THREAD

**Issue by SmartAI** [mdadams/clang_libraries_companion#1]
"llvm::StringRef::endswith_insensitive(llvm::StringRef) const", referenced from:
      clang::Sema::CodeCompleteIncludedFile(llvm::StringRef, bool)::$_13::operator()(llvm::StringRef, bool, clang::DirectoryLookup::LookupType_t) const in libclangSema.a(SemaCodeComplete.cpp.o)
  "llvm::StringRef::startswith_insensitive(llvm::StringRef) const", referenced from:
      clang::driver::Driver::getToolChain(llvm::opt::ArgList const&, llvm::Triple const&) const in libclangDriver.a(Driver.cpp.o)
      computeTargetTriple(clang::driver::Driver const&, llvm::StringRef, llvm::opt::ArgList const&, llvm::StringRef) in libclangDriver.a(Driver.cpp.o)
      clang::driver::tools::OffloadBundler::ConstructJob(clang::driver::Compilation&, clang::driver::JobAction const&, clang::driver::InputInfo const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::opt::ArgList const&, char const*) const in libclangDriver.a(Clang.cpp.o)
      clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(clang::driver::Compilation&, clang::driver::JobAction const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::opt::ArgList const&, char const*) const in libclangDriver.a(Clang.cpp.o)
      clang::Sema::SemaBuiltinARMSpecialReg(unsigned int, clang::CallExpr*, int, unsigned int, bool) in libclangSema.a(SemaChecking.cpp.o)
      clang::driver::tools::riscv::getRISCVArch(llvm::opt::ArgList const&, llvm::Triple const&) in libclangDriver.a(RISCV.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [syntax_check] Error 1
make[4]: *** [CMakeFiles/syntax_check.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ast_consumer_1-prefix/src/ast_consumer_1-stamp/ast_consumer_1-build] Error 2
make[1]: *** [CMakeFiles/ast_consumer_1-build.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Building CXX object CMakeFiles/visitor1.dir/visitor1.cpp.o
[100%] Linking CXX executable matcher
[100%] Linking CXX executable matcher
Undefined symbols for architecture arm64:
[compile.log](https://github.com/mdadams/clang_libraries_companion/files/12320536/compile.log)

**Comment by mdadams** [comment]
The GitHub CI runners test the code under macOS 12 and 13 (as well as Ubuntu).   So, the code should build and run successfully on those systems.  It is my understanding that the GitHub runners for macOS are based on x86-64.  So, it seems likely that your system is ARM-based and this is an ARM issue.  I have no way to debug this type of issue, however, as I have no access to any ARM-based machines running macOS.  I am going to mark this issue as closed, since I have no practical way to debug this issue based on the information that you have provided.  If you do figure out a resolution to the problem and it is due to an error in my build infrastructure, please let me know and I will fix it.  Otherwise, I will have to assume that there is something wrong in your build setup (as opposed to my build infrastructure).
