### ISSUE TITLE
CAL get clang version string failed on MacOS

### ISSUE THREAD

**Issue by SmartAI** [mdadams/clang_libraries_companion#2]
https://github.com/mdadams/clang_libraries_companion/blob/703cbee29a88f335d8dade6e5b0097cca47732b6/miscellany/examples/cal/src/lib/utility.cpp#L210

The code is assuming some specific format when invoke `clang++ --version`. However in MacOS the output of `clang++ --version` is:

```shell
Homebrew clang version 19.1.1
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/19.1.1/bin
```
This will cause the logic failed. 

I would suggest using the following code instead:

```c++
std::string version;
  std::string dummy;

  while (ss >> dummy) {
    if (dummy == "version") {
      ss >> version;
      return version;
    }
  }
```

**Comment by mdadams** [comment]
Maybe a slightly better solution might be to loop over the whitespace-delimited fields on the version line until one of the fields matches a regex for a semantic version like "x", or "x.y", or "x.y.z", where x, y, and z are integers.  I think that the version line should at least always contain a semantic version like this somewhere.  What do you think?

**Comment by SmartAI** [comment]
Yes I think so, this is a more robust way to extract the version. I can fix this issue and send a PR if you agree.

**Comment by mdadams** [comment]
Please note that this public Git repository does not contain the master version of my code.  The master version of the code is stored in a private repository that contains a lot of additional content that is not suitable for public distribution.  This is why all of the commit log messages for this public repository say something generic about synchronizing with an upstream source.  For example, look at the commit log messsage for the followingf commit:  [Synchronize files with the official upstream source.](https://github.com/mdadams/clang_libraries_companion/commit/703cbee29a88f335d8dade6e5b0097cca47732b6).  For this reason, it would not be helpful to submit a PR against this public repository.  If you would like to propose some code changes, you could send me a context diff for your changes.  Since you already have my email address, you could email the context diffs to me directly.
